// Generated by CoffeeScript 1.3.3
(function() {
  var Argument, Argument_List, Arguments_Match, rw, _;

  _ = require("underscore");

  rw = require("rw_ize");

  Argument = require("i_love_u/lib/Argument");

  Arguments_Match = require("i_love_u/lib/Arguments_Match");

  Argument_List = (function() {

    rw.ize(Argument_List);

    Argument_List.read_able("list");

    function Argument_List(raw_str) {
      var full_sentence, str, v;
      str = raw_str.strip();
      full_sentence = str.has_end_period() || str.has_end_colon();
      if (full_sentence) {
        str = str.replace(/\.$/, "").replace(/\:$/, "");
      }
      this.rw_data().list = (function() {
        var _i, _len, _ref, _results;
        _ref = str.whitespace_split();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          v = _ref[_i];
          _results.push(new Argument(v));
        }
        return _results;
      })();
      if (full_sentence) {
        _.first(this.list()).is_start(true);
        _.last(this.list()).is_end(true);
      }
    }

    Argument_List.prototype.compile = function(env, line_n_code, proc) {
      var match;
      match = new Arguments_Match(this, env, line_n_code, proc);
      if (!match.is_a_match()) {
        return null;
      }
      return match;
    };

    return Argument_List;

  })();

  module.exports = Argument_List;

}).call(this);
