// Generated by CoffeeScript 1.3.3
(function() {
  var Env_List, rw;

  rw = require('rw_ize');

  Env_List = (function() {

    Env_List['Local-Env'] = function() {
      return 'Local-Env';
    };

    Env_List['Outside-Env'] = function() {
      return 'Outside-Env';
    };

    rw.ize(Env_List);

    Env_List.read_able('read', 'write', 'outside', 'local');

    function Env_List(local, outside) {
      this.rw('local', local);
      this.rw('outside', outside);
      this.rw('read', outside || local);
      this.rw('write', local);
    }

    Env_List.prototype.has_outside = function() {
      return this.outside() && this.outside() !== "none";
    };

    Env_List.prototype.is_local_only = function() {
      return (!this.has_outside()) || (this.read() === this.local() && this.write() === this.local());
    };

    Env_List.prototype.is_read_local = function() {
      return this.local() === this.read();
    };

    Env_List.prototype.is_write_local = function() {
      return this.local() === this.write();
    };

    Env_List.prototype.read = function(name) {
      if (arguments.length === 0) {
        return this.rw('read');
      }
      return change_env('read', name);
    };

    Env_List.prototype.write = function(name) {
      if (arguments.length === 0) {
        return this.rw('write');
      }
      return change_env('write', name);
    };

    Env_List.prototype.change_env = function(r_or_w, name) {
      if (Env_List[name]) {
        return this.rw(r_or_w, Env_List[name]());
      } else {
        throw new Error("Unknown env called: " + name);
      }
    };

    return Env_List;

  })();

  module.exports = Env_List;

}).call(this);
