// Generated by CoffeeScript 1.3.3
(function() {
  var Env, LOOP_LIMIT, XRegExp;

  XRegExp = require('xregexp').XRegExp;

  Env = require("i_love_u/lib/Env");

  LOOP_LIMIT = 10123;

  if (!RegExp.captures) {
    RegExp.captures = function(r, str) {
      var match, pos, v, vals, _i, _len;
      r.lastIndex = 0;
      match = null;
      vals = [];
      pos = 0;
      while ((match = XRegExp.exec(str, r, pos, 'sticky'))) {
        pos = match.index + match[0].length;
        match.shift();
        for (_i = 0, _len = match.length; _i < _len; _i++) {
          v = match[_i];
          vals.push(v);
        }
      }
      if (vals.length === 0) {
        return null;
      }
      return vals;
    };
  }

  if (!RegExp.first_capture) {
    RegExp.first_capture = function(r, str) {
      var match, vals;
      r.lastIndex = 0;
      match = null;
      vals = null;
      return r.exec(str);
    };
  }

  exports.i_love_u = Env;

}).call(this);
