// Generated by CoffeeScript 1.3.3
(function() {
  var Line, rw, _;

  rw = require("rw_ize");

  _ = require("underscore");

  Line = (function() {

    rw.ize(Line);

    Line.read_able("origin_line", "origin_code");

    Line.read_write_able("line", "code");

    function Line(line, code) {
      this.rw_data("origin_line", line);
      this.rw_data("origin_code", code);
      this.write("line", line);
      this.write("code", code);
    }

    Line.prototype.code_text = function() {
      return this.code() && this.code().text();
    };

    Line.prototype.origin_code_text = function() {
      return this.origin_code() && this.origin_code().text();
    };

    Line.prototype.is_equal_to = function(line) {
      return _.isEqual(this.line(), line.line()) && _.isEqual(this.code_text(), line.code_text());
    };

    Line.prototype.has_changed = function() {
      return _.isEqual(this.origin_line(), this.line()) && _.isEqual(this.origin_code_text(), this.code_text());
    };

    Line.prototype.pair = function() {
      if (this.code()) {
        return [this.line(), this.code()];
      } else {
        return [this.line()];
      }
    };

    Line.prototype.origin_pair = function() {
      if (this.origin_code()) {
        return [this.origin_line(), this.origin_code()];
      } else {
        return [this.origin_line()];
      }
    };

    return Line;

  })();

  module.exports = Line;

}).call(this);
