// Generated by CoffeeScript 1.3.3
(function() {
  var Line, rw, _;

  rw = require("rw_ize");

  _ = require("underscore");

  Line = (function() {

    rw.ize(Line);

    Line.read_able("origin_line", "origin_block");

    Line.read_write_able("line", "block");

    function Line(line, block) {
      this.rw("origin_line", line.slice(0));
      this.rw("origin_block", block);
      this.line(line);
      this.block(block);
    }

    Line.prototype.origin_line_text = function() {
      var new_arr, v, _i, _len, _ref;
      new_arr = [];
      _ref = this.origin_line();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        v = _ref[_i];
        new_arr.push(v.value ? "" + (v.value()) : "" + v);
      }
      return new_arr.join(" ");
    };

    Line.prototype.block_text = function() {
      return this.block() && this.block().text();
    };

    Line.prototype.origin_block_text = function() {
      return this.origin_block() && this.origin_block().text();
    };

    Line.prototype.is_equal_to = function(line) {
      return _.isEqual(this.line(), line.line()) && _.isEqual(this.block_text(), line.block_text());
    };

    Line.prototype.has_changed = function() {
      var same_block, same_line;
      same_line = _.isEqual(this.origin_line(), this.line());
      same_block = _.isEqual(this.origin_block_text(), this.block_text());
      return !same_line || !same_block;
    };

    Line.prototype.pair = function() {
      if (this.block()) {
        return [this.line(), this.block()];
      } else {
        return [this.line()];
      }
    };

    Line.prototype.origin_pair = function() {
      if (this.origin_block()) {
        return [this.origin_line(), this.origin_block()];
      } else {
        return [this.origin_line()];
      }
    };

    return Line;

  })();

  module.exports = Line;

}).call(this);
