// Generated by CoffeeScript 1.3.3
(function() {
  var Line, rw, _;

  rw = require("rw_ize");

  _ = require("underscore");

  Line = (function() {

    rw.ize(Line);

    Line.read_able("origin_line", "origin_block");

    Line.read_write_able("line", "block");

    function Line(line, block) {
      this.rw_data("origin_line", line);
      this.rw_data("origin_block", block);
      this.write("line", line);
      this.write("block", block);
    }

    Line.prototype.block_text = function() {
      return this.block() && this.block().text();
    };

    Line.prototype.origin_block_text = function() {
      return this.origin_block() && this.origin_block().text();
    };

    Line.prototype.is_equal_to = function(line) {
      return _.isEqual(this.line(), line.line()) && _.isEqual(this.block_text(), line.block_text());
    };

    Line.prototype.has_changed = function() {
      return _.isEqual(this.origin_line(), this.line()) && _.isEqual(this.origin_block_text(), this.block_text());
    };

    Line.prototype.pair = function() {
      if (this.block()) {
        return [this.line(), this.block()];
      } else {
        return [this.line()];
      }
    };

    Line.prototype.origin_pair = function() {
      if (this.origin_block()) {
        return [this.origin_line(), this.origin_block()];
      } else {
        return [this.origin_line()];
      }
    };

    return Line;

  })();

  module.exports = Line;

}).call(this);
