// Generated by CoffeeScript 1.3.3
(function() {
  var Argument_List, Procedure, rw;

  rw = require("rw_ize");

  Argument_List = require("i_love_u/lib/Argument_List");

  Procedure = (function() {

    rw.ize(Procedure);

    Procedure.read_write_able('priority', 'pattern', 'data', 'list', 'procedure');

    Procedure.read_able('args_list', 'regexp');

    function Procedure(pattern) {
      this.rw_data().data = {};
      this.rw_data().pattern = pattern;
      this.rw_data().list = [];
      this.rw_data().priority = 'low';
      this.rw_data().args_list = new Argument_List(pattern.strip());
    }

    Procedure.prototype.run = function(env, line_n_code) {
      var match, r;
      match = this.args_list().compile(env, line_n_code);
      if (!match || !match.is_a_match) {
        return line_n_code;
      }
      r = this.procedure()(match);
      return [r.line, r.code];
    };

    return Procedure;

  })();

  module.exports = Procedure;

}).call(this);
