// Generated by CoffeeScript 1.3.3
(function() {
  var Run_Line_Tokens_Response, rw;

  rw = require('rw_ize');

  Run_Line_Tokens_Response = (function() {

    rw.ize(Run_Line_Tokens_Response);

    Run_Line_Tokens_Response.read_able("compiled_line");

    Run_Line_Tokens_Response.read_write_able_bool("is_a_match", "is_a_full_match");

    function Run_Line_Tokens_Response(compiled_line, yield_to) {
      this.rw('compiled_line', compiled_line);
      if (typeof yield_to === "function") {
        yield_to(this);
      }
    }

    Run_Line_Tokens_Response.prototype.is_a_response = function() {
      return true;
    };

    Run_Line_Tokens_Response.prototype.is_a_run_line_tokens_response = function() {
      return true;
    };

    return Run_Line_Tokens_Response;

  })();

  module.exports = Run_Line_Tokens_Response;

}).call(this);
