// Generated by CoffeeScript 1.3.3
(function() {
  var luv, _,
    __slice = [].slice;

  luv = require("i_love_u");

  exports.new_luv = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args), t = typeof result;
      return t == "object" || t == "function" ? result || child : child;
    })(luv.i_love_u, args, function(){});
  };

  _ = require("underscore");

  exports.stack = function(env) {
    return env.vars().array('var_values');
  };

}).call(this);
