// Generated by CoffeeScript 1.3.3
(function() {
  var luv,
    __slice = [].slice;

  luv = require("i_love_u");

  exports.new_luv = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args), t = typeof result;
      return t == "object" || t == "function" ? result || child : child;
    })(luv.i_love_u, args, function(){});
  };

  exports.stack = function(env) {
    var arr, v, _base, _i, _len, _ref;
    arr = [];
    _ref = env.vars();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      v = _ref[_i];
      if (!(typeof (_base = v.value()).is_a_procedure === "function" ? _base.is_a_procedure() : void 0)) {
        arr.push(v.value().values ? obj.value().values() : obj.value());
      }
    }
    return arr;
  };

}).call(this);
